# Задание
Загрузите данные и разделите выборку на обучающую/проверочную в соотношении 80/20.

Примените метод ближайших соседей (kNN) для классификации скоринга, используйте k=100. Используйте биометрические данные, все столбцы Insurance_History, Family_Hist, Medical_History и InsurеdInfo. Заполните отсутствующие значения -1.

Проведите предсказание и проверьте качество через каппа-метрику.

Данные: video.ittensive.com/machine-learning/prudential/train.csv.gz

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import cohen_kappa_score, confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
import re
from etl_utils import reduce_mem_usage, show_inf_and_na, inf_and_na_columns
pd.set_option('display.max_columns', 200)

Загрузите данные.

In [2]:
data_df = reduce_mem_usage(pd.read_csv("https://video.ittensive.com/machine-learning/prudential/train.csv.gz"))
data_df.head()

Потребление памяти меньше на 49.49 Мб (-85.4%)


Id  Product_Info_1 Product_Info_2  Product_Info_3  Product_Info_4  \
0   2               1             D3              10        0.076904   
1   5               1             A1              26        0.076904   
2   6               1             E1              26        0.076904   
3   7               1             D4              10        0.487061   
4   8               1             D2              26        0.230713   

   Product_Info_5  Product_Info_6  Product_Info_7   Ins_Age        Ht  \
0               2               1               1  0.641602  0.582031   
1               2               3               1  0.059692  0.600098   
2               2               3               1  0.029846  0.745605   
3               2               3               1  0.164185  0.672852   
4               2               3               1  0.417969  0.654785   

         Wt       BMI  Employment_Info_1  Employment_Info_2  \
0  0.148560  0.322998           0.028000                 12   
1  0.131836  0.272217           0.000000                  1   
2  0.288818  0.428711           0.029999                  9   
3  0.205078  0.352539           0.041992                  9   
4  0.234253  0.424072           0.026993                  9   

   Employment_Info_3  Employment_Info_4  Employment_Info_5  Employment_Info_6  \
0                  1                0.0                  3                NaN   
1                  3                0.0                  2           0.001800   
2                  1                0.0                  2           0.029999   
3                  1                0.0                  3           0.199951   
4                  1                0.0                  2           0.049988   

   InsuredInfo_1  InsuredInfo_2  InsuredInfo_3  InsuredInfo_4  InsuredInfo_5  \
0              1              2              6              3              1   
1              1              2              6              3              1   
2              1              2              8              3              1   
3              2              2              8              3              1   
4              1              2              6              3              1   

   InsuredInfo_6  InsuredInfo_7  Insurance_History_1  Insurance_History_2  \
0              2              1                    1                    1   
1              2              1                    2                    1   
2              1              1                    2                    1   
3              2              1                    2                    1   
4              2              1                    2                    1   

   Insurance_History_3  Insurance_History_4  Insurance_History_5  \
0                    3                    1             0.000667   
1                    3                    1             0.000133   
2                    1                    3                  NaN   
3                    1                    3                  NaN   
4                    1                    3                  NaN   

   Insurance_History_7  Insurance_History_8  Insurance_History_9  \
0                    1                    1                    2   
1                    1                    3                    2   
2                    3                    2                    3   
3                    3                    2                    3   
4                    3                    2                    3   

   Family_Hist_1  Family_Hist_2  Family_Hist_3  Family_Hist_4  Family_Hist_5  \
0              2            NaN       0.598145            NaN       0.526855   
1              2       0.188354            NaN       0.084534            NaN   
2              3       0.304443            NaN       0.225342            NaN   
3              3       0.420410            NaN       0.352051            NaN   
4              2       0.463867            NaN       0.408447            NaN   

   Medical_History_1  

Используйте биометрические данные, все столбцы Insurance_History, Family_Hist, Medical_History и InsurеdInfo

Заполните отсутствующие значения -1.

In [3]:
feature_regsearcher = r'Insurance_History.*|Family_Hist.*|Medical_History.*|InsuredInfo.*|Wt|Ht|Ins_Age|BMI'
x_features = [feature for feature in data_df.columns if re.match(feature_regsearcher, feature) != None]
data_df[x_features] = data_df[x_features].fillna(-1)
show_inf_and_na(data_df[x_features])

Ins_Age Inf+NaN: 0
Ht Inf+NaN: 0
Wt Inf+NaN: 0
BMI Inf+NaN: 0
InsuredInfo_1 Inf+NaN: 0
InsuredInfo_2 Inf+NaN: 0
InsuredInfo_3 Inf+NaN: 0
InsuredInfo_4 Inf+NaN: 0
InsuredInfo_5 Inf+NaN: 0
InsuredInfo_6 Inf+NaN: 0
InsuredInfo_7 Inf+NaN: 0
Insurance_History_1 Inf+NaN: 0
Insurance_History_2 Inf+NaN: 0
Insurance_History_3 Inf+NaN: 0
Insurance_History_4 Inf+NaN: 0
Insurance_History_5 Inf+NaN: 0
Insurance_History_7 Inf+NaN: 0
Insurance_History_8 Inf+NaN: 0
Insurance_History_9 Inf+NaN: 0
Family_Hist_1 Inf+NaN: 0
Family_Hist_2 Inf+NaN: 0
Family_Hist_3 Inf+NaN: 0
Family_Hist_4 Inf+NaN: 0
Family_Hist_5 Inf+NaN: 0
Medical_History_1 Inf+NaN: 0
Medical_History_2 Inf+NaN: 0
Medical_History_3 Inf+NaN: 0
Medical_History_4 Inf+NaN: 0
Medical_History_5 Inf+NaN: 0
Medical_History_6 Inf+NaN: 0
Medical_History_7 Inf+NaN: 0
Medical_History_8 Inf+NaN: 0
Medical_History_9 Inf+NaN: 0
Medical_History_10 Inf+NaN: 0
Medical_History_11 Inf+NaN: 0
Medical_History_12 Inf+NaN: 0
Medical_History_13 Inf+NaN: 0
Medical_H

Разделите выборку на обучающую/проверочную в соотношении 80/20.

In [4]:
train_df, test_df = train_test_split(data_df, test_size=.2)

Примените метод ближайших соседей (kNN) для классификации скоринга, используйте k=100.

In [5]:
knn = KNeighborsClassifier(n_neighbors=100, n_jobs=-1)
knn.fit(train_df[x_features], train_df['Response'])

KNeighborsClassifier(n_jobs=-1, n_neighbors=100)

Проведите предсказание и проверьте качество через каппа-метрику.

In [6]:
predictions = knn.predict(test_df[x_features])
kappa = cohen_kappa_score(test_df['Response'], predictions, weights='quadratic')
print('knn 100 каппа:', kappa)

knn 100 каппа: 0.12780868053765448


Какое значение каппа метрики получившейся модели с точностью до сотых ?

In [7]:
round(kappa, 2)

0.13

In [8]:
print(confusion_matrix(test_df['Response'], predictions))
del train_df
del test_df
del data_df

[[  80   52    1    5    1  187   50  838]
 [  65   56    1    4    2  184   43  935]
 [   5    2    0    3    0   17    7  157]
 [   3    1    0   13    0   24    4  265]
 [  28   22    0    0    1  145   34  823]
 [  67   57    0    0    4  359   65 1740]
 [  37   22    0    0    1  155   72 1294]
 [  28   15    0    0    2  137   25 3739]]
